### ISSUE TITLE
Packages 'nesc', 'tinyos-tools' and 'msp430-46' throw errors; 'avr-tinyos' is not all installable

### ISSUE THREAD

**Issue by fossterer** [tinyos/tinyos-release#3]
None of the packages listed at the download page 'http://tinyprod.net/repos/debian/' are installable

Outputs:
- sudo apt-get install nesc
  ...
  Error: Package X is trying to overwrite the file Y. File Y is already provided by package Z
  ...
- sudo apt-get install tinyos-tools
  ...
  Unpacking tinyos-tools (1.4.2-tinyprod1) ...
  dpkg: error processing archive tinyos-tools_1.4.2-tinyprod1_i386.deb (--install):
  trying to overwrite '/usr/bin/uisp', which is also in package uisp 20050207-4.2ubuntu1
  dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
  ...
- sudo apt-get install msp430-46
  ...
  Error: Package X is trying to overwrite the file Y. File Y is already provided by package Z
  ...
- sudo apt-get install avr-tinyos
  ...
  dpkg: dependency problems prevent configuration of avr-tinyos:
  avr-tinyos depends on avr-tinyos-base; however:
  Package avr-tinyos-base is not installed.
  avr-tinyos depends on avr-binutils-tinyos; however:
  Package avr-binutils-tinyos is not installed.
  avr-tinyos depends on avr-gcc-tinyos; however:
  Package avr-gcc-tinyos is not installed.
  avr-tinyos depends on avr-libc-tinyos; however:
  Package avr-libc-tinyos is not installed.
  avr-tinyos depends on avrdude-tinyos; however:
  Package avrdude-tinyos is not installed.
  ...

**Comment by cire831** [comment]
Buried on the README page for the tinyprod.net repository are the following instructions for removing old packages first...

You may need to remove old *-tinyos packages. To do so, follow these instructions:

Remove previously installed _-tinyos packages:
  $ sudo dpkg -P `dpkg -l nesc '_tinyos*' | grep ^ii | awk '{ print $2 }' | xargs`
  $ sudo apt-get clean

You may also need to remove other packages that conflict.

The repository installs on a clean/fresh system.

The avr toolchain on tinyprod has known problems.   You need to get the avr toolchain from the stanford site.

We are working on fixing this but it will take some time.
